/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/files/{session_id}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download File
         * @description Public download of a session upload.
         *
         *     No auth: the model gateway must fetch this URL with no token, so the
         *     unguessable session id plus the file name is the bearer capability.
         *     Every hit is audited under the session's owner.
         */
        get: operations["download_file_files__session_id___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process is up. Checks nothing, so it cannot flap.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: DB reachable and cache pingable. Memory is reported alongside
         *     them but does not gate the status. Returns a JSONResponse directly so the
         *     status code can be 503 without raising.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Audit
         * @description Audit history from audit_events, newest first.
         *
         *     Reads MySQL, not the JSONL mirror: history is no longer bounded by the
         *     daily file rotation, and the indexed columns (actor/tool/event) do the
         *     filtering instead of a Python scan. `user` matches both tool_call
         *     records (keyed by username) and auth records (keyed by username);
         *     `limit` is capped at 500 server-side, silently reduced rather than
         *     rejected. Records surface a beat after the audited request: they reach
         *     this table through the async drainer, not on the request path.
         */
        get: operations["admin_audit_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Traces
         * @description Execution traces, newest first: one agent_runs row per POST /runs.
         *
         *     `anomaly=true` keeps only flagged runs (failed / empty / tool storm).
         *     `limit` is capped at 200 server-side. The single-run view
         *     (/v1/admin/traces/{run_id}) carries the steps and the transcript; this
         *     list view omits them so a page stays one query. The prompt is
         *     truncated to 200 chars here - the detail view carries it in full.
         */
        get: operations["admin_traces_v1_admin_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/traces/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Trace
         * @description One run, complete: prompt, capability flags, ordered steps with full
         *     tool arguments and results, and the transcript slice it wrote.
         *
         *     Retention deletes old traces, so a 404 can also mean "older than
         *     PI_TRACE_RETENTION_DAYS". A run whose session was deleted still shows
         *     steps but no messages (the idx range points at rows that are gone).
         */
        get: operations["admin_trace_v1_admin_traces__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Users */
        get: operations["admin_list_users_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Admin Update User
         * @description Partial update: omitted fields are untouched.
         *
         *     Setting is_active=false also bumps the user's revocation epoch, so every
         *     token issued before now is rejected on its next request.
         */
        patch: operations["admin_update_user_v1_admin_users__username__patch"];
        trace?: never;
    };
    "/v1/admin/users/{username}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Revoke User
         * @description Invalidate every active token of a user without disabling the account.
         */
        post: operations["admin_revoke_user_v1_admin_users__username__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Blacklist this token's jti for its remaining lifetime.
         *
         *     The token stays cryptographically valid; revocation is a cache lookup,
         *     so it is lost if the cache is flushed before the token would expire.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Open signup, always a normal user; admin is granted by editing the DB.
         *
         *     Unauthenticated by design, so 8300 must not be reachable from the internet.
         */
        post: operations["register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Whoami: the cheapest way for the client to validate a stored token.
         */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        /**
         * Deregister
         * @description Erase this account and every trace of it.
         *
         *     The full cascade: memory facts and their vector mirror, then messages,
         *     sessions, usage rows, the account row, and the workspace directory. All
         *     interactions leave traces in MySQL by design, so erasing one user means
         *     walking all of them - in FK order, one transaction for the relational
         *     part. A run still streaming for this user fails its next message write
         *     (the session row is gone); that is the accepted behavior, not a crash.
         *
         *     The revocation epoch is bumped last and matters most on re-registration:
         *     a token issued to the deleted account must never authenticate against a
         *     new account created under the same username later.
         */
        delete: operations["deregister_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Memories
         * @description The caller's stored long-term facts, oldest first.
         *
         *     The user id comes from the token and never from a parameter, so there is no
         *     way to ask for somebody else's memory. `limit` is capped server-side at 500.
         */
        get: operations["list_memories_v1_memories_get"];
        put?: never;
        post?: never;
        /**
         * Clear Memories
         * @description Forget everything. This is the erasure endpoint (PIPL art. 47 / GDPR art. 17).
         *
         *     Returns a count rather than a flag so the caller can tell "you had nothing
         *     stored" from "memory is not enabled here" without a second request.
         */
        delete: operations["clear_memories_v1_memories_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Memory
         * @description Forget one fact.
         *
         *     The path id is not authority on its own: the delete is scoped to the caller,
         *     so guessing another tenant's id is a 404 rather than a removal. That also
         *     means the 404 leaks nothing - it is identical for "not yours" and "never
         *     existed".
         */
        delete: operations["delete_memory_v1_memories__fact_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_v1_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description Files uploaded to this session, with their public download URLs.
         */
        get: operations["list_files_v1_sessions__session_id__files_get"];
        put?: never;
        /**
         * Upload File
         * @description Upload a file into this session's workspace.
         *
         *     The file becomes attachable to runs (`RunIn.files`) and downloadable by
         *     anyone holding the returned URL - which is the point: the model gateway
         *     fetches it with no credentials when a run references it.
         */
        post: operations["upload_file_v1_sessions__session_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages
         * @description Full transcript, oldest first.
         *
         *     The `blocks` column holds a whole serialized Message, not a bare block
         *     array: runner.py writes m.model_dump_json() and reads history back with
         *     Message.model_validate_json(). Returning the raw parse therefore nested
         *     a duplicate of the message under `blocks` - parse it as a Message and
         *     take the array.
         */
        get: operations["get_messages_v1_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_v1_sessions__session_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage Summary
         * @description This month's token spend per model, plus the caller's quota position.
         */
        get: operations["usage_summary_v1_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUserListOut */
        AdminUserListOut: {
            /**
             * Users
             * @description Ordered by id, capped at 200.
             */
            users: components["schemas"]["AdminUserOut"][];
        };
        /** AdminUserOut */
        AdminUserOut: {
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Is Admin */
            is_admin: boolean;
            /** Quota Tokens */
            quota_tokens: number;
            /** Username */
            username: string;
        };
        /** AuditOut */
        AuditOut: {
            /**
             * Records
             * @description Newest first. Deliberately untyped: this reads the audit_events table whose payload schema has grown over time (event = tool_call | compaction | auth | memory, all carrying ts), and a strict model would turn one legacy record into a 500.
             */
            records: {
                [key: string]: unknown;
            }[];
        };
        /** Body_upload_file_v1_sessions__session_id__files_post */
        Body_upload_file_v1_sessions__session_id__files_post: {
            /** File */
            file: string;
        };
        /**
         * DeregisterIn
         * @description Password confirmation for DELETE /v1/me.
         *
         *     The bearer token already proves session ownership, but erasure is irreversible
         *     and tokens can be left on a shared machine - a stolen token must not be enough
         *     to erase an account.
         */
        DeregisterIn: {
            /** Password */
            password: string;
        };
        /**
         * DeregisterOut
         * @description DELETE /v1/me. `purged` says what actually went away, per table.
         */
        DeregisterOut: {
            /**
             * Deleted
             * @constant
             */
            deleted: true;
            /**
             * Purged
             * @description Row counts removed per table (memories, messages, sessions, usage_records, account). The workspace directory is deleted even when it held no database rows.
             */
            purged: {
                [key: string]: number;
            };
            /** Username */
            username: string;
        };
        /**
         * ErrorOut
         * @description FastAPI's HTTPException body; every non-2xx below uses this shape.
         */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /**
         * FileBlock
         * @description A file attached to a user message (upload), referenced by public URL.
         *
         *     The gateway downloads the file itself when the request is sent, so this
         *     block only ever carries the URL plus a display name. Only some models
         *     accept it; the provider decides whether to translate it or fail loudly.
         */
        FileBlock: {
            /** File Url */
            file_url: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
        };
        /** FileListOut */
        FileListOut: {
            /**
             * Files
             * @description Sorted by name.
             */
            files: components["schemas"]["FileOut"][];
        };
        /**
         * FileOut
         * @description A file uploaded to a session. `url` is public (no auth) and is what the
         *     model gateway fetches when the file is attached to a run.
         */
        FileOut: {
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LoginOut */
        LoginOut: {
            /** Access Token */
            access_token: string;
            /**
             * Expires In
             * @description Seconds. PI_TOKEN_TTL_MINUTES * 60.
             */
            expires_in: number;
            /**
             * Is Admin
             * @description So the client can show/hide the admin console right after login.
             */
            is_admin: boolean;
            /**
             * Token Type
             * @constant
             */
            token_type: "bearer";
            /**
             * Username
             * @description The stored account name, not an echo of the request. MySQL's default collation matches case-insensitively, so the login form's spelling and the account's spelling can differ.
             */
            username: string;
        };
        /** LogoutOut */
        LogoutOut: {
            /** Revoked */
            revoked: boolean;
            /** Username */
            username: string;
        };
        /** MeOut */
        MeOut: {
            /**
             * Is Admin
             * @description So the client can show/hide the admin console after token restore.
             */
            is_admin: boolean;
            /** Username */
            username: string;
        };
        /** MemoryClearOut */
        MemoryClearOut: {
            /**
             * Deleted
             * @description How many facts this user had; 0 when memory is off.
             */
            deleted: number;
        };
        /** MemoryDeleteOut */
        MemoryDeleteOut: {
            /**
             * Deleted
             * @description Always true; a fact that is not the caller's is a 404.
             * @constant
             */
            deleted: true;
        };
        /**
         * MemoryFactOut
         * @description One stored long-term fact. Text is redacted before it is ever written.
         */
        MemoryFactOut: {
            /** Created At */
            created_at: string;
            /**
             * Id
             * @description Store-local id, unique within this user's facts.
             */
            id: number;
            /**
             * Kind
             * @description preference | convention | environment | fact.
             */
            kind: string;
            /**
             * Source Session
             * @description Session the fact was extracted from.
             */
            source_session: string;
            /** Text */
            text: string;
        };
        /** MemoryListOut */
        MemoryListOut: {
            /**
             * Facts
             * @description Oldest first, capped at 500.
             */
            facts: components["schemas"]["MemoryFactOut"][];
            /**
             * Status
             * @description 'ready', 'disabled' or 'unavailable: <reason>'. 'disabled' with an empty list is the normal state when PI_MILVUS_URI or PI_EMBEDDING_MODEL is unset, not an error.
             */
            status: string;
        };
        /** MessageListOut */
        MessageListOut: {
            /**
             * Messages
             * @description Ordered by idx, oldest first.
             */
            messages: components["schemas"]["MessageOut"][];
        };
        /** MessageOut */
        MessageOut: {
            /** Blocks */
            blocks: (components["schemas"]["TextBlock"] | components["schemas"]["ToolCallBlock"] | components["schemas"]["ToolResultBlock"] | components["schemas"]["FileBlock"])[];
            /**
             * Idx
             * @description 0-based position of the message within the session.
             */
            idx: number;
            role: components["schemas"]["Role"];
        };
        /**
         * Plan
         * @description Structured task plan, produced by the model through the submit_plan tool.
         *
         *     The bounds are load-bearing: this is untrusted model output that gets
         *     persisted into a TEXT column and replayed over SSE. 200 + 20*300 caps a plan
         *     at ~6 KB, which a single column, a single event frame and a 50-session list
         *     response all absorb comfortably.
         *
         *     Steps are plain strings rather than objects. Nothing in this schema tracks
         *     step progress - a status field would be dead weight until the approval and
         *     resume phases give it a lifecycle, and freezing the enum values now would
         *     only have to be undone later.
         */
        Plan: {
            /**
             * Steps
             * @description Ordered, concrete steps.
             */
            steps: string[];
            /**
             * Title
             * @description One-line goal of the task.
             */
            title: string;
        };
        /** ReadyOut */
        ReadyOut: {
            /**
             * Checks
             * @description Per dependency: 'ok', 'unreachable', or 'error: <detail>'.
             */
            checks: {
                [key: string]: string;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not-ready";
        };
        /** RegisterIn */
        RegisterIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** RegisterOut */
        RegisterOut: {
            /** Id */
            id: number;
            /**
             * Is Admin
             * @description Always false. Admin is granted by editing the DB.
             */
            is_admin: boolean;
            /** Username */
            username: string;
        };
        /** RevokeOut */
        RevokeOut: {
            /**
             * Revoked
             * @constant
             */
            revoked: true;
            /** Username */
            username: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "system" | "user" | "assistant";
        /** RunIn */
        RunIn: {
            /**
             * Builtin Tools
             * @description Gateway-executed tools to offer the model this run.
             */
            builtin_tools?: ("web_search" | "web_extractor" | "code_interpreter")[];
            /**
             * Enable Search
             * @description Endpoint-side web search woven into the answer (extra_body.enable_search).
             * @default false
             */
            enable_search: boolean;
            /**
             * Files
             * @description Names of files uploaded to this session to attach to the prompt.
             */
            files?: string[];
            /** Model */
            model?: string | null;
            /** Prompt */
            prompt: string;
        };
        /**
         * SessionCreatedOut
         * @description POST /v1/sessions. cwd is echoed so the client can show where bash runs.
         */
        SessionCreatedOut: {
            /** Cwd */
            cwd: string;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Title */
            title: string;
        };
        /** SessionIn */
        SessionIn: {
            /** Model */
            model?: string | null;
            /**
             * Title
             * @default session
             */
            title: string;
        };
        /** SessionListOut */
        SessionListOut: {
            /**
             * Sessions
             * @description Newest first, capped at 50.
             */
            sessions: components["schemas"]["SessionSummary"][];
        };
        /**
         * SessionSummary
         * @description Body of GET /v1/sessions/{id} and one element of GET /v1/sessions.
         */
        SessionSummary: {
            /**
             * Created At
             * @description UTC ISO-8601, second precision (stored as a string).
             */
            created_at: string;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** @description The session's current plan, or null until submit_plan has run. Both the list and the detail endpoint return it, so a reload shows the same plan the live stream painted. A newer plan replaces an older one; the immutable history is the submit_plan call in the transcript. */
            plan?: components["schemas"]["Plan"] | null;
            /** Title */
            title: string;
        };
        /** SseCompactionData */
        SseCompactionData: {
            /** Chars After */
            chars_after: number;
            /** Chars Before */
            chars_before: number;
            /**
             * Dropped
             * @description Number of messages replaced by the summary.
             */
            dropped: number;
        };
        /**
         * SseDoneData
         * @description End-of-stream marker. Always `{}`.
         */
        SseDoneData: Record<string, never>;
        /** SseErrorData */
        SseErrorData: {
            /**
             * Message
             * @description Emitted inside an HTTP 200 stream: a failed run is an event, not a status code.
             */
            message: string;
        };
        /**
         * SsePlanData
         * @description Inherits Plan instead of re-declaring title/steps, so the bounds live in one place.
         */
        SsePlanData: {
            /**
             * Steps
             * @description Ordered, concrete steps.
             */
            steps: string[];
            /**
             * Title
             * @description One-line goal of the task.
             */
            title: string;
        };
        /** SseStartData */
        SseStartData: {
            /**
             * Model
             * @description The model this turn actually resolved to.
             */
            model: string;
            /** Session */
            session: string;
        };
        /** SseTextDeltaData */
        SseTextDeltaData: {
            /**
             * Text
             * @description One incremental chunk of assistant text.
             */
            text: string;
        };
        /** SseToolCallEndData */
        SseToolCallEndData: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Ok
             * @description False when the tool raised, when the policy denied it, or when a terminal tool earlier in the same batch ended the turn and this call was skipped without executing - in that last case `result` says so, and the tool had no side effects.
             */
            ok: boolean;
            /**
             * Result
             * @description Preview only: AgentLoop cuts it to 200 characters and flattens newlines to spaces before emitting the event. Fetch the full result from GET /v1/sessions/{id}/messages instead.
             */
            result: string;
        };
        /** SseToolCallStartData */
        SseToolCallStartData: {
            /**
             * Id
             * @description Tool call id; matches the id in toolcall_end. Emitted once per streamed argument chunk, so the same id arrives several times - key on the id, do not treat each frame as a new call.
             */
            id: string;
            /** Name */
            name: string;
        };
        /** SseTurnEndData */
        SseTurnEndData: {
            /**
             * Turns
             * @description LLM round-trips this run took, including tool loops.
             */
            turns: number;
            usage: components["schemas"]["Usage"];
        };
        /** TextBlock */
        TextBlock: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        /** ToolCallBlock */
        ToolCallBlock: {
            /**
             * Arguments
             * @default {}
             */
            arguments: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_call";
        };
        /** ToolResultBlock */
        ToolResultBlock: {
            /** Content */
            content: string;
            /**
             * Is Error
             * @default false
             */
            is_error: boolean;
            /** Tool Use Id */
            tool_use_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_result";
        };
        /** TraceListOut */
        TraceListOut: {
            /** Runs */
            runs: components["schemas"]["TraceRunOut"][];
        };
        /** TraceRunOut */
        TraceRunOut: {
            /**
             * Builtin Tools
             * @description Gateway-executed tools this run offered the model.
             */
            builtin_tools?: string[];
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Enable Search
             * @description Model-native web search was on.
             * @default false
             */
            enable_search: boolean;
            /**
             * Ended At
             * @default
             */
            ended_at: string;
            /**
             * Error
             * @default
             */
            error: string;
            /**
             * Failed Tools
             * @default 0
             */
            failed_tools: number;
            /**
             * First Idx
             * @description First message idx this run persisted; null when nothing landed.
             */
            first_idx?: number | null;
            /**
             * Flags
             * @description Anomaly verdict: status name when the run failed, 'empty' when it produced no turns, 'tool_storm' at >= 3 failed tool calls, 'memory_failed' when a retrieval stage raised. An empty recall is not flagged - it is the normal answer for a user with no facts yet. Empty list = unremarkable run.
             */
            flags?: string[];
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /** Last Idx */
            last_idx?: number | null;
            /**
             * Messages
             * @description Only /v1/admin/traces/{run_id} fills this: the full transcript slice this run wrote (first_idx..last_idx) - input, assistant output, tool calls with arguments and results, attachments.
             */
            messages?: components["schemas"]["MessageOut"][] | null;
            /** Model */
            model: string;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Prompt
             * @description The user's input, verbatim. The list view truncates to 200 chars.
             * @default
             */
            prompt: string;
            /**
             * Request Id
             * @description Matches X-Request-Id and the access-log line.
             * @default
             */
            request_id: string;
            /**
             * Run Id
             * @description 12-hex id; also the /v1/admin/traces/{run_id} key
             */
            run_id: string;
            /** Session Id */
            session_id: string;
            /** Started At */
            started_at: string;
            /**
             * Status
             * @description ok | error | timeout
             */
            status: string;
            /**
             * Steps
             * @description Only /v1/admin/traces/{run_id} fills this; the list view omits it.
             */
            steps?: components["schemas"]["TraceStepOut"][] | null;
            /**
             * Turns
             * @default 0
             */
            turns: number;
            /** Username */
            username: string;
        };
        /** TraceStepOut */
        TraceStepOut: {
            /**
             * Args
             * @description Full JSON arguments of the tool call (tool_call steps), or the query retrieval selected facts for (retrieval steps). Empty otherwise.
             * @default
             */
            args: string;
            /**
             * Detail
             * @description Full result content for tool_call steps. For retrieval, the whole account as JSON: outcome, which recall path ran, every candidate with its cosine and rerank scores and why it was dropped, per-stage milliseconds, and the text actually injected - the only record of it, since injected memory never enters the transcript. For llm_call, turn, stop_reason, tokens, duration and error as JSON. The plan title or the error message for those kinds. Never the SSE preview.
             * @default
             */
            detail: string;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Kind
             * @description tool_call | retrieval | llm_call | plan | compaction | error. retrieval is the long-term-memory lookup before the first model call (at most one per run); llm_call is one per model round-trip, including the one that raised.
             */
            kind: string;
            /**
             * Name
             * @description Tool name, 'memory.retrieve', or an llm_call's model.
             * @default
             */
            name: string;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Seq
             * @description order within the run, 0-based
             */
            seq: number;
            /**
             * Ts
             * @default
             */
            ts: string;
        };
        /** Usage */
        Usage: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
        };
        /** UsageModelOut */
        UsageModelOut: {
            /** Est Cost Usd */
            est_cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /** Runs */
            runs: number;
        };
        /** UsageOut */
        UsageOut: {
            /** Models */
            models: components["schemas"]["UsageModelOut"][];
            /**
             * Month
             * @description 'YYYY-MM' in UTC.
             */
            month: string;
            /**
             * Quota Tokens
             * @description Effective monthly quota: the user's own, or PI_DEFAULT_QUOTA_TOKENS when that is 0.
             */
            quota_tokens: number;
            /** Total Est Cost Usd */
            total_est_cost_usd: number;
            /** Total Input Tokens */
            total_input_tokens: number;
            /** Total Output Tokens */
            total_output_tokens: number;
            /** Used Tokens */
            used_tokens: number;
        };
        /** UserUpdateIn */
        UserUpdateIn: {
            /** Is Active */
            is_active?: boolean | null;
            /** Quota Tokens */
            quota_tokens?: number | null;
        };
        /** UserUpdateOut */
        UserUpdateOut: {
            /**
             * Changed
             * @description Which fields this call actually wrote; empty if the body was {}.
             */
            changed: ("quota_tokens" | "is_active")[];
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    download_file_files__session_id___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such session. Ownership is part of the lookup, so another user's session is also 404 and never 403 - the existence of an id is not leaked across accounts. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description DB or cache is not 'ok'. Same body as 200, with status 'not-ready'. The memory entry is reported but never triggers this. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    admin_audit_v1_admin_audit_get: {
        parameters: {
            query?: {
                user?: string | null;
                tool?: string | null;
                event?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Authenticated but not an admin. is_admin is granted by writing the users table directly; no endpoint can grant it. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_traces_v1_admin_traces_get: {
        parameters: {
            query?: {
                user?: string | null;
                session?: string | null;
                status?: string | null;
                anomaly?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Authenticated but not an admin. is_admin is granted by writing the users table directly; no endpoint can grant it. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_trace_v1_admin_traces__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceRunOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Authenticated but not an admin. is_admin is granted by writing the users table directly; no endpoint can grant it. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description No run with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_users_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Authenticated but not an admin. is_admin is granted by writing the users table directly; no endpoint can grant it. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_update_user_v1_admin_users__username__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserUpdateOut"];
                };
            };
            /** @description 'cannot disable yourself' - the last admin must not be able to lock the panel out. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Authenticated but not an admin. is_admin is granted by writing the users table directly; no endpoint can grant it. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description No such username. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_revoke_user_v1_admin_users__username__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Authenticated but not an admin. is_admin is granted by writing the users table directly; no endpoint can grant it. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description No such username. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description 'invalid credentials' for an unknown username or a wrong password (deliberately indistinguishable), 'account disabled' only when the password was correct - so the second message does not enumerate accounts either. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterOut"];
                };
            };
            /** @description Username does not match ^[a-zA-Z0-9_-]{2,32}$. The password bounds are enforced earlier, by the request body schema (422). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Username already exists - including a signup that lost the race to an identical one. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    deregister_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeregisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeregisterOut"];
                };
            };
            /** @description 'password confirmation failed' (the token alone must not be enough for irreversible erasure), or 'cannot delete the last admin'. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_v1_memories_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryListOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_memories_v1_memories_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryClearOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    delete_memory_v1_memories__fact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDeleteOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description No such fact - including one that exists but belongs to another user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreatedOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description No such session. Ownership is part of the lookup, so another user's session is also 404 and never 403 - the existence of an id is not leaked across accounts. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_v1_sessions__session_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description No such session. Ownership is part of the lookup, so another user's session is also 404 and never 403 - the existence of an id is not leaked across accounts. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_v1_sessions__session_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_v1_sessions__session_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description PI_PUBLIC_BASE_URL is not set, or the file name is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description No such session. Ownership is part of the lookup, so another user's session is also 404 and never 403 - the existence of an id is not leaked across accounts. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description File exceeds the PI_MAX_UPLOAD_BYTES limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_v1_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description No such session. Ownership is part of the lookup, so another user's session is also 404 and never 403 - the existence of an id is not leaked across accounts. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_v1_sessions__session_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /**
             * @description Server-Sent Events, over **POST** - so `EventSource` cannot be used. Read
             *     `response.body` with a `ReadableStream` reader, buffer on blank lines, and take
             *     the `event:` / `data:` fields of each frame (a leading `:` is a comment).
             *
             *     One turn emits `start`, then any number of `text_delta`, `toolcall_start`,
             *     `toolcall_end` and `compaction`, then at most one `plan`, then `turn_end`, then
             *     `done`. `error` can arrive at any point **and the HTTP status is still 200**, so a
             *     client that only checks `response.ok` will silently swallow failed runs.
             *
             *     Within a turn the agent loop streams text first, then tool calls, then runs each
             *     tool in order - so a `text_delta` arriving *after* a `toolcall_end` means a new
             *     assistant message has begun. There is no message-boundary event; a client that
             *     rebuilds a transcript has to infer the boundary that way.
             *
             *     `plan` comes after the last `toolcall_end` and before `turn_end`. It is emitted by
             *     `submit_plan`, a terminal tool, so the run ends right after it - at most one per
             *     run. The same plan is persisted and returned as
             *     `GET /v1/sessions/{id}`'s `plan` field, so painting it from the stream and reading
             *     it back after a reload agree.
             *
             *     A run cut short that way still emits exactly one `toolcall_end` for every
             *     `toolcall_start`, including the calls it skipped; those carry `ok: false` and a
             *     `result` saying they never executed. No call is ever left looking like it is still
             *     running.
             *
             *     The `data` payload of each frame is the matching `Sse*Data` schema below; the
             *     event name is *not* repeated inside the JSON.
             *
             *     Forward compatibility: an event type this version of the server does not know
             *     how to serialize is emitted as `event: unknown` with `{}`. Clients must ignore
             *     event names they do not recognise instead of failing on them, so a newer server
             *     can add events without breaking an older browser tab.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseStartData"] | components["schemas"]["SseTextDeltaData"] | components["schemas"]["SseToolCallStartData"] | components["schemas"]["SseToolCallEndData"] | components["schemas"]["SseCompactionData"] | components["schemas"]["SsePlanData"] | components["schemas"]["SseTurnEndData"] | components["schemas"]["SseErrorData"] | components["schemas"]["SseDoneData"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Monthly token quota exhausted. The detail carries the used/limit figures; GET /v1/usage returns them as numbers. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description No such session. Ownership is part of the lookup, so another user's session is also 404 and never 403 - the existence of an id is not leaked across accounts. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Per-user fixed-window run limit (PI_RATE_LIMIT_RUNS_PER_MIN) exceeded. */
            429: {
                headers: {
                    /** @description Whole seconds to wait, always at least 1. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    usage_summary_v1_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOut"];
                };
            };
            /** @description Missing, malformed, expired or revoked bearer token - or the account was disabled or deleted since the token was issued. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
